name: RMA MacOS
on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      -
        name: test RMA
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: "Run My App.xcworkspace"
          scheme: "Run My App"
          destination: platform=macOS
          action: build
